version: '3'
services:
  shop_api_db:
    image: 'postgres:12'
    hostname: shop_api_db
    environment:
      - POSTGRES_DB=shop_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - '5437:5432'
    volumes:
      - 'shop-data:/var/lib/postgres-data'

  shop_api:
    build:
      context: .
    command: sh -c 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - '8001:8000'
    depends_on:
      - shop_api_db
volumes:
  shop-data:
